# Como utilizar essa publicação {- #como-utilizar}  

Este documento atende à Resolução Conama nº 462, de 24 de julho de 2014, que atribui ao Instituto Chico Mendes de Conservação da Biodiversidade - ICMBio a responsabilidade pela publicação de um relatório apresentando as áreas regulares de rota, pouso, descanso, alimentação e reprodução de aves migratórias. Estas áreas, aqui tratadas por “Áreas de Concentração para Aves Migratórias”, estão representadas na Figura 7.10 e os seus respectivos arquivos digitais com sua localização geográfica precisa estão disponíveis para *download* em [arquivos no formato .shp](https://www.icmbio.gov.br/cemave/destaques-e-noticias/240-cemave-publica-relatorio-sobre-rotas-de-aves-migratorias.html). Este relatório também pode ser encontrado no [Portal do ICMBio](https://www.icmbio.gov.br/portal/) na *internet* e no [painel *on-line*](https://cemave-sede.github.io/painel-aves-migratorias/#vis%C3%A3o-geral) criado especificamente para o compartilhamento de seu conteúdo. As áreas representadas estão sujeitas às obrigações legais estabelecidas pela Resolução acima citada.  

As Áreas de Concentração para Aves Migratórias foram apontadas pela priorização espacial pelo uso do *software* Zonation de áreas com registro de aves migratórias, sendo complementadas pelos registros de literatura ou de comunicação pessoal por especialistas de áreas de expressiva agregação de indivíduos. Vale ressalvar que o mapeamento realizado não contemplou o ambiente marinho e as lagunas costeiras, de modo que os resultados apresentados não representam todas as áreas importantes para aves migratórias no país.  

O modelo produzido é um indicativo para os órgãos licenciadores de áreas que devem receber especial atenção quando da elaboração de estudos vinculados a licenciamento ambiental. Contudo, como será discutido adiante, existem ainda diversas lacunas de conhecimento acerca da interação das aves migratórias com empreendimentos eólicos e esse documento não esgota o assunto.  

Estudos prévios à instalação de empreendimentos em áreas não representadas na Figura 7.10, mesmo que simplificados, são necessários  para se avaliar a ocorrência de espécies migratórias *in loco*, pois este relatório não contempla informações detalhadas sobre migração de aves para todo o país em nível local.  

Além das Áreas de Concentração de Aves Migratórias, como preconizado na Resolução Conama nº 462/14, esta publicação traz também alguns temas associados.  Apresentamos um mapa com as áreas de ocorrência de espécies de aves ameaçadas (Figura 3.3), com base em compilação realizada pelo CEMAVE a partir de registros de diferentes bancos de dados. Tendo em vista que morcegos são animais bastante impactados por empreendimentos eólicos, disponibilizamos uma análise da relação desse grupo com os empreendimentos eólicos *onshore*. Por fim, oferecemos ao leitor um capítulo com uma visão geral sobre complexos eólicos *offshore*. Visamos, assim, fornecer aos empreendedores e órgãos licenciadores informações especializadas e atualizadas que contribuam para compatibilizar os interesses socioeconômicos e ambientais na geração e distribuição de energia elétrica no Brasil.