# Apêndice B {- #apendiceB}


B1. Algumas normas, diretrizes e orientações relacionadas ao planejamento, implantação e operação de empreendimentos eólicos.  


•	**Lei nº 6.938/1981** - Dispõe sobre as diretrizes da Política Nacional de Meio Ambiente.  

•	**Resolução CONAMA nº 002/1985** – Licenciamento de Atividades Potencialmente Poluidoras.  

•	**Resolução CONAMA nº 001/1986** – Dispõe sobre critérios básicos e diretrizes gerais para a avaliação de impacto ambiental.  

•	**Resolução CONAMA nº 006/1987** - Dispõe sobre o licenciamento ambiental de obras do setor de geração de energia elétrica de grande porte.  

•	**Resolução CONAMA nº 237/1997** - Regulamenta os aspectos de licenciamento ambiental estabelecidos na Política Nacional do Meio Ambiente.  

•	**Lei nº 9.605/1998** - Dispõe sobre as sanções penais e administrativas lesivas ao meio ambiente, em seu artigo 60, estabelece a obrigatoriedade do licenciamento ambiental das atividades degradadoras da qualidade ambiental, contendo, inclusive, as penalidades a serem aplicadas ao infrator.  

•	**Resolução CONAMA nº 279/2001** – Estabelece procedimento simplificado para o licenciamento ambiental de empreendimentos com impacto ambiental de pequeno porte (usinas hidrelétricas e sistemas associados; usinas termelétricas e sistemas associados; sistemas de transmissão de energia elétrica - linhas de transmissão e subestações e usinas eólicas e outras fontes alternativas de energia), necessários ao incremento da oferta de energia elétrica no País, nos termos do Art. 8º, § 3º, da Medida Provisória nº 2.152-2, de 1º de junho de 2001.  

•	**Resolução CONAMA nº 369/2006** - Dispõe sobre os casos excepcionais, de utilidade pública, interesse social ou baixo impacto ambiental, que possibilitam a intervenção ou supressão de vegetação em Área de Preservação Permanente-APP.  

•	**Lei nº 12651/2012** - Dispõe sobre a proteção da vegetação nativa; altera as Leis nºs 6.938, de 31 de agosto de 1981, 9.393, de 19 de dezembro de 1996, e 11.428, de 22 de dezembro de 2006; revoga as Leis nºs 4.771, de 15 de setembro de 1965, e 7.754, de 14 de abril de 1989, e a Medida Provisória nº 2.166-67, de 24 de agosto de 2001; e dá outras providências.  

•	**Decreto Legislativo nº 387/2013** - Aprova o texto da Convenção sobre a Conservação das Espécies Migratórias de Animais Silvestres - CMS, assinado em Bonn, em 23 de junho de 1979.  

•	**Resolução Conama nº 462/2014** – Estabelece procedimentos para o licenciamento ambiental de empreendimentos de geração de energia elétrica a partir de fonte eólica em superfície terrestre, altera o art. 1º da Resolução CONAMA n.º 279, de 27 de julho de 2001, e dá outras providências.  

•	**Portaria MMA nº 444/2014** - Reconhece e apresenta a “Lista Nacional Oficial de Espécies da Fauna Ameaçadas de Extinção”.  

•	**Instrução Normativa ICMBIO nº 07/2014** - Estabelece procedimentos do Instituto Chico Mendes de Conservação da Biodiversidade nos processos de licenciamento ambiental.  

•	**Resolução Normativa nº 876/2020** - Estabelece os requisitos e procedimentos necessários à obtenção de outorga de autorização para exploração e à alteração da capacidade instalada de centrais geradoras Eólicas, Fotovoltaicas, Termelétricas e outras fontes alternativas e à comunicação de implantação de centrais geradoras com capacidade instalada reduzida.  

•	**Convenção sobre a Conservação de Espécies Migratórias de Animais Selvagens** – É um tratado ambiental das Nações Unidas que fornece uma plataforma global para a conservação e uso sustentável de animais migratórios e seus habitat. O CMS reúne os Estados pelos quais passam os animais migratórios, os Estados da área de distribuição, e estabelece a base legal para medidas de conservação coordenadas internacionalmente em toda a área de distribuição migratória.  

•	**Portal Nacional de Licenciamento Ambiental – PNLA** - Instrumento de divulgação de informações sobre o licenciamento ambiental em âmbito nacional que visa atender ao disposto na Lei Nº 10.650, de 16 de abril de 2003, que determina o acesso público aos dados e informações ambientais existentes nos órgãos e entidades que compõem o Sistema Nacional de Meio Ambiente – SISNAMA.  

•	**Planos de Ação Nacional para a Conservação de Espécies de Aves Silvestres Ameaçadas de Extinção - PANs** - Os Planos de Ação Nacional para a Conservação das Espécies da Fauna (PANs) são diretrizes pactuadas com a sociedade para proteger a fauna, priorizando ações de combate às ameaças que põem em risco populações de espécies e ambientes naturais.  


